# Generated by Django 5.2.8 on 2026-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexa', '0004_add_device_id_to_history_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyentry',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
